(function(){
  'use strict';
  const $=selector=>document.querySelector(selector);let orders=[],current=null,token=sessionStorage.getItem('westtechha-admin-token')||'';
  const PRODUCTION=['PRODUCTION_QUEUE','IN_PRODUCTION','PREPARING_TO_SHIP','PREPARING_FOR_PICKUP','READY_FOR_PICKUP','SHIPPED','COMPLETED'];
  const REVIEW=['REQUEST_RECEIVED','UNDER_REVIEW','NEEDS_CUSTOMER_INFO','ON_HOLD','CHANGES_REQUESTED'];
  const money=value=>Number.isFinite(Number(value))?Number(value):0;
  const formatMoney=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(money(value));
  const formatDate=value=>{const date=new Date(value);return !value||Number.isNaN(date.getTime())?'—':date.toLocaleString();};
  const readable=value=>String(value||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const headers=extra=>({Accept:'application/json',Authorization:`Bearer ${token}`,...(extra||{})});
  function notice(id,text,type=''){const el=$(id);el.hidden=!text;el.textContent=text;el.className=`ca-inline-message ${type}`.trim();}
  async function api(path,options={}){const response=await fetch(path,{...options,headers:headers(options.headers)}),data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.message||'Request failed.');return data;}
  function upsert(order){current=order;const index=orders.findIndex(row=>row.orderId===order.orderId);if(index>=0)orders[index]={...orders[index],...order};else orders.unshift(order);renderDetail();}
  function filtered(){const q=$('#ea-search').value.trim().toLowerCase(),filter=$('#ea-filter').value;return orders.filter(order=>{const status=String(order.status||'').toUpperCase(),filterOk=filter==='ALL'||(filter==='ACTIVE'&&!['COMPLETED','ARCHIVED'].includes(status))||status===filter,qOk=!q||[order.orderId,order.customerName,order.customerEmail,order.model,order.sku].some(value=>String(value||'').toLowerCase().includes(q));return filterOk&&qOk;});}
  function renderList(){const rows=filtered();$('#ea-count').textContent=`${rows.length} order${rows.length===1?'':'s'}`;const list=$('#ea-order-list');if(!rows.length){list.innerHTML='<div class="ca-empty">No enclosure orders match this view.</div>';return;}list.innerHTML=rows.map(order=>`<button class="ca-order-item${current?.orderId===order.orderId?' active':''}" type="button" data-order="${esc(order.orderId)}"><div class="ea-order-meta"><b>${esc(readable(order.status))}</b><time>${esc(formatDate(order.createdAt))}</time></div><strong>${esc(order.orderId)}</strong><span>${esc(order.customerName)} • ${Number(order.quantity||1)} × ${esc(order.model)}</span></button>`).join('');list.querySelectorAll('[data-order]').forEach(button=>button.addEventListener('click',()=>selectOrder(button.dataset.order)));}
  function renderTotal(){const shipping=$('#ea-fulfillment').value==='LOCAL_PICKUP'?0:money($('#ea-shipping').value),total=Math.max(0,money($('#ea-product-amount').value)+money($('#ea-custom-charge').value)+shipping-money($('#ea-discount').value));$('#ea-total').textContent=formatMoney(total);return total;}
  function termsFrozen(){const status=String(current?.status||'').toUpperCase();return ['CONFIGURATION_SENT','CONFIGURATION_APPROVED','AWAITING_PAYMENT',...PRODUCTION,'ARCHIVED'].includes(status)||String(current?.paymentStatus||'').toUpperCase()==='PAID';}
  function setReviewFields(){
    const frozen=termsFrozen(),ids=['ea-status','ea-fulfillment','ea-payment-required','ea-printer-minutes','ea-printer','ea-production-window','ea-product-amount','ea-custom-charge','ea-shipping','ea-discount','ea-customer-message'];ids.forEach(id=>$('#'+id).disabled=frozen);$('#ea-admin-notes').disabled=false;
    const select=$('#ea-status');if(![...select.options].some(option=>option.value===current.status))select.add(new Option(readable(current.status),current.status));select.value=current.status;$('#ea-fulfillment').value=current.fulfillmentMethod||'UNSET';$('#ea-payment-required').checked=current.paymentRequired!==false;$('#ea-printer-minutes').value=String(current.estimatedPrinterMinutes||0);$('#ea-printer').value=current.printerAssignment||'';$('#ea-production-window').value=current.productionWindow||'';$('#ea-product-amount').value=money(current.productAmount||current.startingSubtotal).toFixed(2);$('#ea-custom-charge').value=money(current.customCharge).toFixed(2);$('#ea-shipping').value=money(current.shippingAmount).toFixed(2);$('#ea-discount').value=money(current.discountAmount).toFixed(2);$('#ea-customer-message').value=current.customerReviewNote||'';$('#ea-admin-notes').value=current.adminNotes||'';
    $('#ea-review-lock').textContent=frozen?'Customer terms locked':'No payment is collected in this phase.';$('#ea-review-note').innerHTML=frozen?'<strong>Customer terms are locked.</strong> Configuration, pricing, fulfillment, and production window cannot change here. Internal notes remain available.':'<strong>Review phase.</strong> Save the configuration, final subtotal, fulfillment method, and production window before sending it to the customer.';$('#ea-save').textContent=frozen?'Save Internal Note':'Save Enclosure Review';renderTotal();
  }
  function renderRelease(){const status=String(current.status||'').toUpperCase(),sent=!!current.configurationSentAt,awaiting=status==='CONFIGURATION_SENT',card=$('#ea-release-card'),eligible=REVIEW.includes(status)||awaiting;card.hidden=!eligible;if(!eligible)return;$('#ea-version').textContent=sent?`VERSION ${current.configurationVersion} • LAST SENT ${formatDate(current.configurationSentAt)}`:'NOT SENT';$('#ea-refresh-link').hidden=!awaiting;$('#ea-send-terms').hidden=awaiting;$('#ea-release-title').textContent=status==='CHANGES_REQUESTED'||(REVIEW.includes(status)&&sent)?'Send updated configuration and terms':awaiting?'Configuration and terms sent':'Send configuration and terms';$('#ea-release-copy').textContent=status==='CHANGES_REQUESTED'||(REVIEW.includes(status)&&sent)?'Review the requested changes, save the revised terms, then send a new locked configuration version.':awaiting?'The private link is active. Resend creates a fresh private link without changing the customer terms.':'Send a private page where the customer can approve the configuration, price, fulfillment method, and production window.';}
  function renderState(){const pay=String(current.paymentStatus||'NOT_REQUESTED').toUpperCase();$('#ea-payment-pill').textContent=readable(pay);$('#ea-config-state').textContent=current.configurationVersion?`Version ${current.configurationVersion} • ${current.configurationApprovedAt?'Approved':'Awaiting approval'}`:'Not sent';$('#ea-config-time').textContent=current.configurationApprovedAt?`Approved ${formatDate(current.configurationApprovedAt)}`:(current.configurationSentAt?`Sent ${formatDate(current.configurationSentAt)}`:'—');$('#ea-fulfillment-state').textContent=current.fulfillmentMethod==='LOCAL_PICKUP'?'Local Pickup':current.fulfillmentMethod==='SHIP'?'Ship Order':'Not confirmed';$('#ea-window-state').textContent=current.productionWindow||'Production window not set';$('#ea-payment-total').textContent=formatMoney(current.paymentTotal||current.finalAmount);$('#ea-tax-state').textContent=current.taxPreparedAt?`Tax ${formatMoney(current.taxAmount)} • ${current.taxSource||'calculated'}`:'Tax not prepared';$('#ea-paypal-state').textContent=current.paypalOrderId?`${current.paypalOrderStatus||'CREATED'} • ${current.paypalOrderId}`:(current.paymentRequired?'Not created':'Not required');$('#ea-paypal-time').textContent=current.paypalPaidAt?`Paid ${formatDate(current.paypalPaidAt)}`:(current.paypalLastError||'—');$('#ea-sync-paypal').hidden=!current.paypalOrderId||pay==='PAID';const address=$('#ea-address'),lines=[current.shippingName,current.shippingAddress1,current.shippingAddress2,[current.shippingCity,current.shippingRegion,current.shippingPostalCode].filter(Boolean).join(', ').replace(`, ${current.shippingPostalCode||''}`,` ${current.shippingPostalCode||''}`)].filter(Boolean);address.hidden=!lines.length;address.textContent=lines.length?`SHIP TO\n${lines.join('\n')}`:'';}
  function productionChoices(){const status=String(current.status||'').toUpperCase();let next='';if(status==='PRODUCTION_QUEUE')next='IN_PRODUCTION';else if(status==='IN_PRODUCTION')next=current.fulfillmentMethod==='LOCAL_PICKUP'?'PREPARING_FOR_PICKUP':'PREPARING_TO_SHIP';else if(status==='PREPARING_FOR_PICKUP')next='READY_FOR_PICKUP';else if(status==='PREPARING_TO_SHIP')next='SHIPPED';else if(['READY_FOR_PICKUP','SHIPPED'].includes(status))next='COMPLETED';return [status,next].filter(Boolean);}
  function renderProduction(){const status=String(current.status||'').toUpperCase(),visible=PRODUCTION.includes(status),form=$('#ea-production-form');form.hidden=!visible;if(!visible)return;$('#ea-production-status').innerHTML=productionChoices().map(value=>`<option value="${value}">${readable(value)}</option>`).join('');$('#ea-production-status').value=status;$('#ea-production-printer').value=current.printerAssignment||'';$('#ea-carrier').value=current.trackingCarrier||'';$('#ea-tracking').value=current.trackingNumber||'';const shipping=current.fulfillmentMethod==='SHIP';$('#ea-carrier').disabled=!shipping;$('#ea-tracking').disabled=!shipping;$('#ea-save-production').disabled=status==='COMPLETED';}
  function renderArchive(){const status=String(current.status||'').toUpperCase(),card=$('#ea-archive-card');card.hidden=!['COMPLETED','ARCHIVED'].includes(status);if(card.hidden)return;const archived=status==='ARCHIVED';$('#ea-archive-title').textContent=archived?'Archived order':'Completed order';$('#ea-archive-copy').textContent=archived?'Restore this complete record to the Completed view.':'Archive this finished order to remove it from Active while keeping the complete customer, payment, production, work-log, and event record.';$('#ea-archive').textContent=archived?'Restore Order':'Archive Order';}
  function renderWork(){const rows=current.workLog||[],total=rows.reduce((sum,row)=>sum+Number(row.minutes||0),0);$('#ea-work-total').textContent=`${total} min`;const root=$('#ea-work-list');root.innerHTML=rows.length?rows.map(row=>`<div class="ea-work-entry"><strong>${esc(readable(row.workType))}</strong><span>${Number(row.minutes||0)} min</span><span>${esc(row.note||'—')}</span><time>${esc(formatDate(row.createdAt))}</time></div>`).join(''):'<div class="ca-empty">No work logged yet.</div>';$('#ea-work-form').hidden=String(current.status).toUpperCase()==='ARCHIVED';}
  function renderEvents(){const events=current.events||[],root=$('#ea-events');root.innerHTML=events.length?events.map(event=>{let detail=event.detail||'';try{const parsed=JSON.parse(detail);detail=Object.entries(parsed).map(([key,value])=>`${readable(key)}: ${value}`).join(' • ');}catch(e){}return `<div class="ea-event"><strong>${esc(readable(event.eventType))}</strong><span>${esc(detail||'—')}<small>${esc(formatDate(event.createdAt))}</small></span></div>`;}).join(''):'<div class="ca-empty">No order history yet.</div>';}
  function renderDetail(){if(!current)return;$('#ea-loading').hidden=true;$('#ea-detail').hidden=false;$('#ea-order-id').textContent=current.orderId;$('#ea-order-created').textContent=`Submitted ${formatDate(current.createdAt)} • Updated ${formatDate(current.updatedAt)}`;$('#ea-status-pill').textContent=readable(current.status);$('#ea-customer').textContent=current.customerName;$('#ea-contact').textContent=[current.customerEmail,current.customerPhone].filter(Boolean).join(' • ');$('#ea-configuration').textContent=`${current.quantity} × ${current.model} ${current.boardVariant}`;$('#ea-options').textContent=`${current.offerType} • ${current.color} • ${readable(current.fulfillmentPreference)} preference`;$('#ea-starting-total').textContent=formatMoney(current.startingSubtotal);$('#ea-customer-notes').textContent=current.customerNotes||'No customer notes.';const change=$('#ea-change-request');change.hidden=!current.customerChangeRequest;change.textContent=current.customerChangeRequest?`CUSTOMER CHANGE REQUEST: ${current.customerChangeRequest}`:'';setReviewFields();renderRelease();renderState();renderProduction();renderArchive();renderWork();renderEvents();renderList();}
  async function selectOrder(orderId){notice('#ea-message','');$('#ea-loading').hidden=false;$('#ea-loading').textContent='Loading enclosure order…';$('#ea-detail').hidden=true;try{const data=await api(`/api/admin/enclosures/orders/${encodeURIComponent(orderId)}`);current=data.order;const url=new URL(location.href);url.searchParams.set('order',current.orderId);history.replaceState(null,'',url);renderDetail();}catch(error){$('#ea-loading').textContent=error.message;}}
  async function loadOrders(){const list=$('#ea-order-list');list.innerHTML='<div class="ca-empty">Loading enclosure orders…</div>';try{const data=await api('/api/admin/enclosures/orders');orders=data.orders||[];renderList();const requested=new URLSearchParams(location.search).get('order'),target=requested&&orders.some(row=>row.orderId===requested)?requested:(current?.orderId||orders[0]?.orderId);if(target)await selectOrder(target);else $('#ea-loading').textContent='No enclosure orders yet.';}catch(error){list.innerHTML=`<div class="ca-empty">${esc(error.message)}</div>`;$('#ea-loading').textContent='Connect with the WestTech admin token.';}}
  async function postMain(payload){return api(`/api/admin/enclosures/orders/${encodeURIComponent(current.orderId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});}
  async function saveReview(event){event.preventDefault();const button=$('#ea-save'),frozen=termsFrozen();button.disabled=true;button.textContent='Saving…';notice('#ea-message','');const payload={action:'saveReview',status:$('#ea-status').value,fulfillmentMethod:$('#ea-fulfillment').value,paymentRequired:$('#ea-payment-required').checked,estimatedPrinterMinutes:money($('#ea-printer-minutes').value),printerAssignment:$('#ea-printer').value.trim(),productionWindow:$('#ea-production-window').value.trim(),productAmount:money($('#ea-product-amount').value),customCharge:money($('#ea-custom-charge').value),shippingAmount:money($('#ea-shipping').value),discountAmount:money($('#ea-discount').value),customerReviewNote:$('#ea-customer-message').value.trim(),adminNotes:$('#ea-admin-notes').value.trim()};try{const data=await postMain(payload);upsert(data.order);notice('#ea-message',frozen?'Internal note saved. Customer terms remain locked.':'Enclosure review saved. Nothing has been sent to the customer yet.','success');}catch(error){notice('#ea-message',error.message,'error');}finally{button.disabled=false;button.textContent=frozen?'Save Internal Note':'Save Enclosure Review';}}
  async function release(action){const button=action==='refreshLink'?$('#ea-refresh-link'):$('#ea-send-terms'),original=button.textContent;button.disabled=true;button.textContent=action==='refreshLink'?'Resending…':'Sending…';notice('#ea-release-message','');try{const data=await api(`/api/admin/enclosures/orders/${encodeURIComponent(current.orderId)}/approval`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});upsert(data.order);notice('#ea-release-message',data.email?.sent?'Private approval page sent to the customer.':'The private page was created, but the email needs review.','success');}catch(error){notice('#ea-release-message',error.message,'error');}finally{button.disabled=false;button.textContent=original;}}
  async function syncPayPal(){const button=$('#ea-sync-paypal'),original=button.textContent;button.disabled=true;button.textContent='Syncing…';try{const data=await api(`/api/admin/enclosures/orders/${encodeURIComponent(current.orderId)}/paypal`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'sync'})});upsert(data.order);}catch(error){notice('#ea-message',error.message,'error');}finally{button.disabled=false;button.textContent=original;}}
  async function saveProduction(event){event.preventDefault();const button=$('#ea-save-production'),original=button.textContent;button.disabled=true;button.textContent='Saving…';notice('#ea-production-message','');try{const data=await postMain({action:'saveReview',status:$('#ea-production-status').value,printerAssignment:$('#ea-production-printer').value.trim(),trackingCarrier:$('#ea-carrier').value.trim(),trackingNumber:$('#ea-tracking').value.trim(),adminNotes:$('#ea-admin-notes').value.trim()});upsert(data.order);notice('#ea-production-message','Production status saved. The customer was emailed if the status changed.','success');}catch(error){notice('#ea-production-message',error.message,'error');}finally{button.disabled=false;button.textContent=original;}}
  async function archive(){const archived=String(current.status).toUpperCase()==='ARCHIVED',button=$('#ea-archive'),original=button.textContent;button.disabled=true;button.textContent=archived?'Restoring…':'Archiving…';try{const data=await postMain({action:archived?'restoreArchive':'archive'});upsert(data.order);}catch(error){notice('#ea-message',error.message,'error');}finally{button.disabled=false;button.textContent=original;}}
  async function addWork(event){event.preventDefault();const button=$('#ea-add-work'),original=button.textContent;button.disabled=true;button.textContent='Adding…';notice('#ea-work-message','');try{const data=await postMain({action:'addWork',workType:$('#ea-work-type').value,minutes:money($('#ea-work-minutes').value),note:$('#ea-work-note').value.trim()});upsert(data.order);$('#ea-work-minutes').value='0';$('#ea-work-note').value='';notice('#ea-work-message','Work entry added.','success');}catch(error){notice('#ea-work-message',error.message,'error');}finally{button.disabled=false;button.textContent=original;}}
  $('#ea-token').value=token;$('#ea-connect').addEventListener('click',()=>{token=$('#ea-token').value.trim();if(token){sessionStorage.setItem('westtechha-admin-token',token);loadOrders();}});$('#ea-token').addEventListener('keydown',event=>{if(event.key==='Enter')$('#ea-connect').click();});$('#ea-search').addEventListener('input',renderList);$('#ea-filter').addEventListener('change',renderList);['ea-product-amount','ea-custom-charge','ea-shipping','ea-discount'].forEach(id=>$('#'+id).addEventListener('input',renderTotal));$('#ea-fulfillment').addEventListener('change',()=>{if($('#ea-fulfillment').value==='LOCAL_PICKUP')$('#ea-shipping').value='0.00';renderTotal();});$('#ea-review-form').addEventListener('submit',saveReview);$('#ea-send-terms').addEventListener('click',()=>release('sendTerms'));$('#ea-refresh-link').addEventListener('click',()=>release('refreshLink'));$('#ea-sync-paypal').addEventListener('click',syncPayPal);$('#ea-production-form').addEventListener('submit',saveProduction);$('#ea-archive').addEventListener('click',archive);$('#ea-work-form').addEventListener('submit',addWork);if(token)loadOrders();
})();
