(function(){
  'use strict';
  const $=selector=>document.querySelector(selector);
  let orders=[],current=null,token=sessionStorage.getItem('westtechha-admin-token')||'';
  const money=value=>Number.isFinite(Number(value))?Number(value):0;
  const formatMoney=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(money(value));
  const formatDate=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?String(value||'—'):d.toLocaleString();};
  const readable=value=>String(value||'').replaceAll('_',' ');
  const headers=extra=>({'Accept':'application/json','Authorization':`Bearer ${token}`,...(extra||{})});
  function message(text,type=''){const el=$('#ea-message');el.hidden=!text;el.textContent=text;el.className=`ca-inline-message ${type}`.trim();}
  async function api(path,options={}){const response=await fetch(path,{...options,headers:headers(options.headers)});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.message||'Request failed.');return data;}
  function filterOrders(){const q=$('#ea-search').value.trim().toLowerCase(),filter=$('#ea-filter').value;return orders.filter(order=>{const status=String(order.status||'').toUpperCase();const filterOk=filter==='ALL'||(filter==='ACTIVE'&&!['COMPLETED','ARCHIVED','CANCELLED'].includes(status))||status===filter;const qOk=!q||[order.orderId,order.customerName,order.customerEmail,order.model,order.sku].some(v=>String(v||'').toLowerCase().includes(q));return filterOk&&qOk;});}
  function renderList(){const rows=filterOrders();$('#ea-count').textContent=`${rows.length} order${rows.length===1?'':'s'}`;const list=$('#ea-order-list');if(!rows.length){list.innerHTML='<div class="ca-empty">No enclosure requests match this view.</div>';return;}list.innerHTML=rows.map(order=>`<button class="ca-order-item${current?.orderId===order.orderId?' active':''}" type="button" data-order="${order.orderId}"><div class="ea-order-meta"><b>${readable(order.status)}</b><time>${formatDate(order.createdAt)}</time></div><strong>${order.orderId}</strong><span>${order.customerName} • ${order.quantity} × ${order.model}</span></button>`).join('');list.querySelectorAll('[data-order]').forEach(button=>button.addEventListener('click',()=>selectOrder(button.dataset.order)));}
  function renderTotal(){const total=Math.max(0,money($('#ea-product-amount').value)+money($('#ea-custom-charge').value)+money($('#ea-shipping').value)-money($('#ea-discount').value));$('#ea-total').textContent=formatMoney(total);return total;}
  function renderEvents(){const root=$('#ea-events'),events=current?.events||[];if(!events.length){root.innerHTML='<div class="ca-empty">No order history yet.</div>';return;}root.innerHTML=events.map(event=>{let detail=event.detail||'';try{const parsed=JSON.parse(detail);detail=Object.entries(parsed).map(([key,value])=>`${readable(key)}: ${value}`).join(' • ');}catch(e){}return `<div class="ea-event"><strong>${readable(event.eventType)}</strong><span>${detail||'—'}<small>${formatDate(event.createdAt)}</small></span></div>`;}).join('');}
  function renderDetail(){if(!current)return;$('#ea-loading').hidden=true;$('#ea-detail').hidden=false;$('#ea-order-id').textContent=current.orderId;$('#ea-order-created').textContent=`Submitted ${formatDate(current.createdAt)} • Updated ${formatDate(current.updatedAt)}`;$('#ea-status-pill').textContent=readable(current.status);$('#ea-customer').textContent=current.customerName;$('#ea-contact').textContent=[current.customerEmail,current.customerPhone].filter(Boolean).join(' • ');$('#ea-configuration').textContent=`${current.quantity} × ${current.model} ${current.boardVariant}`;$('#ea-options').textContent=`${current.offerType} • ${current.color} • ${readable(current.fulfillmentPreference)} preference`;$('#ea-starting-total').textContent=formatMoney(current.startingSubtotal);$('#ea-customer-notes').textContent=current.customerNotes||'No customer notes.';$('#ea-status').value=current.status;$('#ea-fulfillment').value=current.fulfillmentMethod||'UNSET';$('#ea-printer-minutes').value=String(current.estimatedPrinterMinutes||0);$('#ea-printer').value=current.printerAssignment||'';$('#ea-production-window').value=current.productionWindow||'';$('#ea-product-amount').value=money(current.productAmount||current.startingSubtotal).toFixed(2);$('#ea-custom-charge').value=money(current.customCharge).toFixed(2);$('#ea-shipping').value=money(current.shippingAmount).toFixed(2);$('#ea-discount').value=money(current.discountAmount).toFixed(2);$('#ea-customer-message').value=current.customerReviewNote||'';$('#ea-admin-notes').value=current.adminNotes||'';renderTotal();renderEvents();renderList();}
  async function selectOrder(orderId){message('');$('#ea-loading').hidden=false;$('#ea-loading').textContent='Loading enclosure request…';$('#ea-detail').hidden=true;try{const data=await api(`/api/admin/enclosures/orders/${encodeURIComponent(orderId)}`);current=data.order;const url=new URL(location.href);url.searchParams.set('order',current.orderId);history.replaceState(null,'',url);renderDetail();}catch(error){$('#ea-loading').textContent=error.message;}}
  async function loadOrders(){const list=$('#ea-order-list');list.innerHTML='<div class="ca-empty">Loading enclosure requests…</div>';try{const data=await api('/api/admin/enclosures/orders');orders=data.orders||[];renderList();const requested=new URLSearchParams(location.search).get('order');const target=requested&&orders.some(o=>o.orderId===requested)?requested:(current?.orderId||orders[0]?.orderId);if(target)await selectOrder(target);else{$('#ea-loading').textContent='No enclosure requests yet.';}}catch(error){list.innerHTML=`<div class="ca-empty">${error.message}</div>`;$('#ea-loading').textContent='Connect with the WestTech admin token.';}}
  async function save(event){event.preventDefault();if(!current)return;message('');const button=$('#ea-save');button.disabled=true;button.textContent='Saving Review…';const payload={action:'saveReview',status:$('#ea-status').value,fulfillmentMethod:$('#ea-fulfillment').value,estimatedPrinterMinutes:money($('#ea-printer-minutes').value),printerAssignment:$('#ea-printer').value.trim(),productionWindow:$('#ea-production-window').value.trim(),productAmount:money($('#ea-product-amount').value),customCharge:money($('#ea-custom-charge').value),shippingAmount:money($('#ea-shipping').value),discountAmount:money($('#ea-discount').value),customerReviewNote:$('#ea-customer-message').value.trim(),adminNotes:$('#ea-admin-notes').value.trim()};try{const data=await api(`/api/admin/enclosures/orders/${encodeURIComponent(current.orderId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});current=data.order;const index=orders.findIndex(o=>o.orderId===current.orderId);if(index>=0)orders[index]={...orders[index],...current};renderDetail();message('Enclosure review saved. No customer approval or payment was released.','success');}catch(error){message(error.message,'error');}finally{button.disabled=false;button.textContent='Save Enclosure Review';}}
  $('#ea-token').value=token;$('#ea-connect').addEventListener('click',()=>{token=$('#ea-token').value.trim();if(token){sessionStorage.setItem('westtechha-admin-token',token);loadOrders();}});$('#ea-token').addEventListener('keydown',event=>{if(event.key==='Enter')$('#ea-connect').click();});$('#ea-search').addEventListener('input',renderList);$('#ea-filter').addEventListener('change',renderList);['ea-product-amount','ea-custom-charge','ea-shipping','ea-discount'].forEach(id=>$('#'+id).addEventListener('input',renderTotal));$('#ea-review-form').addEventListener('submit',save);if(token)loadOrders();
})();
