(function(){
  'use strict';
  const $=selector=>document.querySelector(selector);let token=sessionStorage.getItem('westtechha-admin-token')||'',data={orders:[],settings:{},summary:{}};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const readable=value=>String(value||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
  const hours=minutes=>`${(Number(minutes||0)/60).toFixed(Number(minutes||0)%60?1:0)} hr`;
  const formatDate=value=>{const d=new Date(value);return !value||Number.isNaN(d.getTime())?'—':d.toLocaleString();};
  const headers=extra=>({Accept:'application/json',Authorization:`Bearer ${token}`,...(extra||{})});
  function message(text,type=''){const el=$('#wo-message');el.hidden=!text;el.textContent=text;el.className=`wo-message ca-inline-message ${type}`.trim();}
  async function api(options={}){const response=await fetch('/api/admin/work-orders',{...options,headers:headers(options.headers)}),json=await response.json().catch(()=>({}));if(!response.ok||!json.ok)throw new Error(json.message||'Could not load shared work orders.');return json;}
  function adminUrl(order){return order.sourceType==='COASTER'?`coaster-orders.html?order=${encodeURIComponent(order.sourceOrderId)}`:`enclosure-orders.html?order=${encodeURIComponent(order.sourceOrderId)}`;}
  function filtered(){const q=$('#wo-search').value.trim().toLowerCase(),filter=$('#wo-filter').value;return (data.orders||[]).filter(order=>{const status=String(order.status||'').toUpperCase(),printing=['PRODUCTION_QUEUE','IN_PRODUCTION'].includes(status),complete=['COMPLETED','ARCHIVED'].includes(status),match=filter==='ALL'||(filter==='ACTIVE'&&printing&&!order.isPaused)||(filter==='PAUSED'&&order.isPaused)||(filter==='COMPLETED'&&complete)||filter===order.sourceType;return match&&(!q||[order.sourceOrderId,order.customerName,order.itemSummary,order.status].join(' ').toLowerCase().includes(q));});}
  function renderSummary(){const summary=data.summary||{},settings=data.settings||{};$('#wo-active').textContent=String(summary.activeOrderCount??0);$('#wo-hours').textContent=hours(summary.remainingPrinterMinutes);$('#wo-printers').textContent=String(settings.activePrinters??2);$('#wo-capacity').textContent=hours(summary.capacityMinutesPerDay);$('#wo-setting-printers').value=String(settings.activePrinters??2);$('#wo-setting-minutes').value=String(settings.productiveMinutesPerPrinterDay??1200);$('#wo-setting-handling').value=String(settings.handlingBusinessDays??2);$('#wo-setting-span').value=String(settings.windowSpanBusinessDays??2);}
  function render(){renderSummary();const rows=filtered(),list=$('#wo-list');if(!rows.length){list.innerHTML='<div class="ca-card wo-empty">No shared work orders match this view.</div>';return;}list.innerHTML=rows.map(order=>{const active=['PRODUCTION_QUEUE','IN_PRODUCTION'].includes(String(order.status||'')),position=order.isPaused?'Ⅱ':active?(order.queuePosition||'—'):'✓';return `<article class="ca-card wo-row" data-type="${esc(order.sourceType)}" data-order="${esc(order.sourceOrderId)}"><div class="wo-position"><span>${active?'FIFO':'STATE'}</span><strong>${position}</strong></div><div class="wo-order"><span class="wo-status${order.isPaused?' paused':''}">${esc(order.isPaused?'PAUSED':readable(order.status))}</span><a href="${adminUrl(order)}">${esc(order.sourceOrderId)}</a><span>${esc(order.sourceType==='COASTER'?'Coaster':'Enclosure')} • Queued ${esc(formatDate(order.queuedAt))}</span></div><div class="wo-item"><strong>${esc(order.itemSummary)}</strong><span>${esc(order.customerName)} • ${esc(order.fulfillmentMethod==='LOCAL_PICKUP'?'Local pickup':'Ship order')}</span><span>Promised: ${esc(order.promisedWindow||'Not recorded')}</span></div><div class="wo-time"><strong>${hours(order.remainingPrinterMinutes)} remaining</strong><span>${hours(order.estimatedPrinterMinutes)} estimated</span><span>${order.projectedWindow?`Projected ship: ${esc(order.projectedWindow)}`:'Printing complete'}</span></div><form class="wo-edit"><label>Estimated minutes<input name="estimated" type="number" min="0" max="1000000" value="${Number(order.estimatedPrinterMinutes||0)}"/></label><label>Remaining minutes<input name="remaining" type="number" min="0" max="1000000" value="${Number(order.remainingPrinterMinutes||0)}"/></label><label>Printer<select name="printer"><option value="UNASSIGNED">Unassigned</option><option value="K2_1"${order.printerAssignment==='K2_1'?' selected':''}>K2 #1</option><option value="K2_2"${order.printerAssignment==='K2_2'?' selected':''}>K2 #2</option><option value="BOTH"${order.printerAssignment==='BOTH'?' selected':''}>Both K2s</option></select></label><label class="wo-pause"><input name="paused" type="checkbox"${order.isPaused?' checked':''}/> Pause without losing FIFO time</label><label class="wide">Pause reason<input name="reason" maxlength="500" value="${esc(order.pauseReason)}" placeholder="Required when paused"/></label><button class="ca-secondary" type="submit">Save Work Order</button></form></article>`;}).join('');list.querySelectorAll('.wo-edit').forEach(form=>form.addEventListener('submit',saveWorkOrder));}
  async function load(){message('');try{data=await api();render();}catch(error){message(error.message,'error');}}
  async function saveWorkOrder(event){event.preventDefault();const form=event.currentTarget,row=form.closest('[data-order]'),button=form.querySelector('button'),original=button.textContent;button.disabled=true;button.textContent='Saving…';try{data=await api({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'updateWorkOrder',sourceType:row.dataset.type,sourceOrderId:row.dataset.order,estimatedPrinterMinutes:Number(form.elements.estimated.value||0),remainingPrinterMinutes:Number(form.elements.remaining.value||0),printerAssignment:form.elements.printer.value,isPaused:form.elements.paused.checked,pauseReason:form.elements.reason.value.trim()})});render();message('Shared work order saved. FIFO order remains based on its original queue time.','success');}catch(error){message(error.message,'error');button.disabled=false;button.textContent=original;}}
  async function saveSettings(event){event.preventDefault();const button=event.currentTarget.querySelector('button'),original=button.textContent;button.disabled=true;button.textContent='Saving…';try{data=await api({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'updateSettings',activePrinters:Number($('#wo-setting-printers').value),productiveMinutesPerPrinterDay:Number($('#wo-setting-minutes').value),handlingBusinessDays:Number($('#wo-setting-handling').value),windowSpanBusinessDays:Number($('#wo-setting-span').value)})});render();message('Capacity settings saved and all projected ship windows recalculated. Customer-promised windows were not changed.','success');}catch(error){message(error.message,'error');}finally{button.disabled=false;button.textContent=original;}}
  $('#wo-token').value=token;$('#wo-connect').addEventListener('click',()=>{token=$('#wo-token').value.trim();if(token){sessionStorage.setItem('westtechha-admin-token',token);load();}});$('#wo-token').addEventListener('keydown',event=>{if(event.key==='Enter')$('#wo-connect').click();});$('#wo-filter').addEventListener('change',render);$('#wo-search').addEventListener('input',render);$('#wo-refresh').addEventListener('click',load);$('#wo-settings-form').addEventListener('submit',saveSettings);if(token)load();
})();
