import { requireOrdersDb } from './orders.js';
import { syncManufacturingWorkOrder } from './manufacturing-work-orders.js';

const REVIEW_STATUSES=new Set(['DRAFT','ON_HOLD','NEEDS_CUSTOMER_INFO','CHANGES_REQUESTED']);
const PRODUCTION_STATUSES=new Set(['PRODUCTION_QUEUE','IN_PRODUCTION','PREPARING_TO_SHIP','PREPARING_FOR_PICKUP','READY_FOR_PICKUP','SHIPPED','COMPLETED']);
const FROZEN_STATUSES=new Set(['ORDER_SENT','ORDER_APPROVED','AWAITING_PAYMENT',...PRODUCTION_STATUSES]);
const FULFILLMENT_METHODS=new Set(['UNSET','SHIP','LOCAL_PICKUP']);
const PRINTERS=new Set(['UNASSIGNED','K2_1','K2_2','BOTH']);
const TRACKING_CARRIERS=new Map([['USPS','USPS'],['UPS','UPS'],['FEDEX','FedEx'],['DHL','DHL']]);
const FORWARD_STATUS={PRODUCTION_QUEUE:'IN_PRODUCTION',IN_PRODUCTION:{SHIP:'PREPARING_TO_SHIP',LOCAL_PICKUP:'PREPARING_FOR_PICKUP'},PREPARING_TO_SHIP:'SHIPPED',PREPARING_FOR_PICKUP:'READY_FOR_PICKUP',SHIPPED:'COMPLETED',READY_FOR_PICKUP:'COMPLETED'};

export function clean(value,max=500){return String(value??'').trim().slice(0,max);}
export function number(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
export function integer(value,min=0,max=999999){return Math.min(max,Math.max(min,Math.round(number(value,min))));}
export function money(value){return Math.round(Math.max(0,number(value,0))*100)/100;}
export function makeError(message,status=400){return Object.assign(new Error(message),{status});}
function nowIso(){return new Date().toISOString();}
function utcDate(){return nowIso().slice(0,10).replaceAll('-','');}
function json(value){try{return JSON.stringify(value??{});}catch{return '{}';}}
function bool(value){return value===true||value===1||String(value).toLowerCase()==='true';}
function validEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);}
function newToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return [...bytes].map(value=>value.toString(16).padStart(2,'0')).join('');}
function tokenExpiry(days=90){const date=new Date();date.setUTCDate(date.getUTCDate()+days);return date.toISOString();}
export async function sha256(value){const data=new TextEncoder().encode(String(value)),digest=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');}
function normalizeCarrier(value){return TRACKING_CARRIERS.get(clean(value,100).toUpperCase().replace(/[^A-Z0-9]/g,''))||'';}
function normalizePrinter(value){const p=clean(value,40).toUpperCase();return PRINTERS.has(p)?p:'UNASSIGNED';}

export function normalizeCustomLineItems(value,{required=false}={}){
  let rows=value;
  if(typeof rows==='string'){try{rows=JSON.parse(rows);}catch{rows=[];}}
  if(!Array.isArray(rows))rows=[];
  const items=rows.slice(0,100).map((row,index)=>{
    const description=clean(row?.description,240),quantity=integer(row?.quantity,1,9999),unitAmount=money(row?.unitAmount),taxable=row?.taxable!==false;
    if(!description)return null;
    return {id:clean(row?.id,80)||`line-${index+1}`,description,quantity,unitAmount,taxable,lineTotal:money(quantity*unitAmount)};
  }).filter(Boolean);
  if(required&&!items.length)throw makeError('Add at least one custom order line item.');
  return items;
}

export function calculateCustomAmounts(lineItems,discountValue=0,shippingValue=0){
  const items=normalizeCustomLineItems(lineItems),subtotal=money(items.reduce((sum,item)=>sum+item.lineTotal,0)),taxableBeforeDiscount=money(items.filter(item=>item.taxable).reduce((sum,item)=>sum+item.lineTotal,0)),discountAmount=Math.min(subtotal,money(discountValue)),shippingAmount=money(shippingValue),itemAmount=money(subtotal-discountAmount),taxableRatio=subtotal>0?taxableBeforeDiscount/subtotal:0,taxableAmount=money(Math.max(0,taxableBeforeDiscount-(discountAmount*taxableRatio))),finalAmount=money(itemAmount+shippingAmount);
  return {items,subtotalAmount:subtotal,taxableAmountBeforeDiscount:taxableBeforeDiscount,discountAmount,shippingAmount,itemAmount,taxableAmount,finalAmount};
}

function mapCustomer(row){if(!row)return null;return {id:Number(row.id),displayName:row.display_name,companyName:row.company_name||'',contactName:row.contact_name||'',email:row.email,phone:row.phone||'',defaultFulfillmentMethod:row.default_fulfillment_method||'UNSET',pricingNotes:row.pricing_notes||'',internalNotes:row.internal_notes||'',isActive:!!Number(row.is_active),createdAt:row.created_at,updatedAt:row.updated_at};}
export async function listCustomCustomers(env,{includeInactive=false}={}){const db=requireOrdersDb(env),result=await db.prepare(`SELECT * FROM custom_customers ${includeInactive?'':`WHERE is_active=1`} ORDER BY lower(display_name),id`).all();return (result?.results||[]).map(mapCustomer);}
export async function getCustomCustomer(env,id){const row=await requireOrdersDb(env).prepare(`SELECT * FROM custom_customers WHERE id=? LIMIT 1`).bind(integer(id,1,2147483647)).first();return mapCustomer(row);}
export async function saveCustomCustomer(env,body={}){
  const db=requireOrdersDb(env),id=integer(body?.id,0,2147483647),companyName=clean(body?.companyName,160),contactName=clean(body?.contactName,160),displayName=clean(body?.displayName,180)||companyName||contactName,email=clean(body?.email,254).toLowerCase(),phone=clean(body?.phone,60),fulfillment=clean(body?.defaultFulfillmentMethod,30).toUpperCase()||'UNSET';
  if(displayName.length<2)throw makeError('Enter the customer or company name.');if(!validEmail(email))throw makeError('Enter a valid customer email address.');if(!FULFILLMENT_METHODS.has(fulfillment))throw makeError('Choose a valid default fulfillment method.');
  if(id){const existing=await getCustomCustomer(env,id);if(!existing)throw makeError('Customer not found.',404);await db.prepare(`UPDATE custom_customers SET display_name=?,company_name=?,contact_name=?,email=?,phone=?,default_fulfillment_method=?,pricing_notes=?,internal_notes=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(displayName,companyName||null,contactName||null,email,phone||null,fulfillment,clean(body?.pricingNotes,2500)||null,clean(body?.internalNotes,4000)||null,body?.isActive===false?0:1,id).run();return getCustomCustomer(env,id);}
  const created=await db.prepare(`INSERT INTO custom_customers (display_name,company_name,contact_name,email,phone,default_fulfillment_method,pricing_notes,internal_notes) VALUES (?,?,?,?,?,?,?,?) RETURNING id`).bind(displayName,companyName||null,contactName||null,email,phone||null,fulfillment,clean(body?.pricingNotes,2500)||null,clean(body?.internalNotes,4000)||null).first();return getCustomCustomer(env,created.id);
}

async function allocateOrderId(db){const date=utcDate(),row=await db.prepare(`INSERT INTO custom_order_counters (order_date,last_value) VALUES (?,1001) ON CONFLICT(order_date) DO UPDATE SET last_value=last_value+1 RETURNING last_value`).bind(date).first(),sequence=Number(row?.last_value||1001);return {orderId:`WTX-${date}-${sequence}`,orderDate:date,dailySequence:sequence};}
function parseJsonArray(value){try{const parsed=JSON.parse(String(value||'[]'));return Array.isArray(parsed)?parsed:[];}catch{return [];}}
function mapOrder(row){if(!row)return null;return {id:Number(row.id),orderId:row.order_id,orderDate:row.order_date,dailySequence:Number(row.daily_sequence),customerId:Number(row.customer_id||0),status:row.status,customerName:row.customer_name,customerEmail:row.customer_email,customerPhone:row.customer_phone||'',title:row.title,lineItems:parseJsonArray(row.line_items_json),customerNote:row.customer_note||'',adminNotes:row.admin_notes||'',fulfillmentMethod:row.fulfillment_method||'UNSET',paymentRequired:!!Number(row.payment_required),productionRequired:row.production_required===undefined?true:!!Number(row.production_required),subtotalAmount:number(row.subtotal_amount),taxableAmountBeforeDiscount:number(row.taxable_amount_before_discount),discountAmount:number(row.discount_amount),shippingAmount:number(row.shipping_amount),finalAmount:number(row.final_amount),estimatedPrinterMinutes:Number(row.estimated_printer_minutes||0),printerAssignment:row.printer_assignment||'UNASSIGNED',productionWindow:row.production_window||'',orderVersion:Number(row.order_version||0),approvalExpiresAt:row.approval_expires_at||'',orderSentAt:row.order_sent_at||'',orderApprovedAt:row.order_approved_at||'',changesRequestedAt:row.changes_requested_at||'',customerChangeRequest:row.customer_change_request||'',paymentStatus:row.payment_status||'NOT_REQUESTED',paypalOrderId:row.paypal_order_id||'',paypalApprovalUrl:row.paypal_approval_url||'',paypalOrderStatus:row.paypal_order_status||'',paypalCaptureId:row.paypal_capture_id||'',paypalPaidAt:row.paypal_paid_at||'',paypalLastError:row.paypal_last_error||'',taxableAmount:number(row.taxable_amount),taxAmount:number(row.tax_amount),taxRate:number(row.tax_rate),taxJurisdictionCode:row.tax_jurisdiction_code||'',taxSource:row.tax_source||'',taxAddressSource:row.tax_address_source||'',taxAddressJson:row.tax_address_json||'',taxQuoteJson:row.tax_quote_json||'',paymentTotal:number(row.payment_total),taxPreparedAt:row.tax_prepared_at||'',taxConfirmedAt:row.tax_confirmed_at||'',shippingName:row.shipping_name||'',shippingAddress1:row.shipping_address1||'',shippingAddress2:row.shipping_address2||'',shippingCity:row.shipping_city||'',shippingRegion:row.shipping_region||'',shippingPostalCode:row.shipping_postal_code||'',shippingCountry:row.shipping_country||'US',trackingCarrier:row.tracking_carrier||'',trackingNumber:row.tracking_number||'',pickupReadyAt:row.pickup_ready_at||'',shippedAt:row.shipped_at||'',completedAt:row.completed_at||'',archivedAt:row.archived_at||'',createdAt:row.created_at,updatedAt:row.updated_at};}
async function eventsFor(db,orderId){const result=await db.prepare(`SELECT id,event_type,detail,created_at FROM custom_order_events WHERE order_id=? ORDER BY created_at DESC,id DESC`).bind(orderId).all();return (result?.results||[]).map(row=>({id:row.id,eventType:row.event_type,detail:row.detail||'',createdAt:row.created_at}));}
async function workFor(db,orderId){const result=await db.prepare(`SELECT id,work_type,minutes,note,created_at FROM custom_order_work_log WHERE order_id=? ORDER BY created_at DESC,id DESC`).bind(orderId).all();return (result?.results||[]).map(row=>({id:row.id,workType:row.work_type,minutes:Number(row.minutes||0),note:row.note||'',createdAt:row.created_at}));}
export async function logCustomEvent(db,orderId,eventType,detail){await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,?,?)`).bind(orderId,eventType,json(detail)).run();}
export async function getCustomOrderDetail(env,orderId){const db=requireOrdersDb(env),row=await db.prepare(`SELECT * FROM custom_orders WHERE order_id=? LIMIT 1`).bind(clean(orderId,80)).first();if(!row)throw makeError('Custom order not found.',404);const order=mapOrder(row);order.events=await eventsFor(db,order.orderId);order.workLog=await workFor(db,order.orderId);return order;}
export async function listCustomOrders(env,limit=200){const result=await requireOrdersDb(env).prepare(`SELECT * FROM custom_orders ORDER BY created_at DESC,id DESC LIMIT ?`).bind(integer(limit,1,300)).all();return (result?.results||[]).map(mapOrder);}

export async function createCustomOrder(env,body={}){
  const db=requireOrdersDb(env),customer=await getCustomCustomer(env,body?.customerId);if(!customer||!customer.isActive)throw makeError('Choose an active customer.');const title=clean(body?.title,200)||'Custom WestTech Order',fulfillment=clean(body?.fulfillmentMethod,30).toUpperCase()||customer.defaultFulfillmentMethod||'UNSET';if(!FULFILLMENT_METHODS.has(fulfillment))throw makeError('Choose a valid fulfillment method.');const items=normalizeCustomLineItems(body?.lineItems),shipping=fulfillment==='LOCAL_PICKUP'?0:money(body?.shippingAmount),amounts=calculateCustomAmounts(items,body?.discountAmount,shipping),ids=await allocateOrderId(db),productionRequired=body?.productionRequired!==false,estimatedMinutes=productionRequired?(integer(body?.estimatedPrinterMinutes,1,1000000)||360):0,printerAssignment=productionRequired?normalizePrinter(body?.printerAssignment):'UNASSIGNED',productionWindow=productionRequired?(clean(body?.productionWindow,160)||null):null;
  await db.prepare(`INSERT INTO custom_orders (order_id,order_date,daily_sequence,customer_id,status,customer_name,customer_email,customer_phone,title,line_items_json,customer_note,admin_notes,fulfillment_method,payment_required,production_required,subtotal_amount,taxable_amount_before_discount,discount_amount,shipping_amount,final_amount,estimated_printer_minutes,printer_assignment,production_window) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(ids.orderId,ids.orderDate,ids.dailySequence,customer.id,'DRAFT',customer.displayName,customer.email,customer.phone||null,title,json(amounts.items),clean(body?.customerNote,3000)||null,clean(body?.adminNotes,5000)||null,fulfillment,body?.paymentRequired===false?0:1,productionRequired?1:0,amounts.subtotalAmount,amounts.taxableAmountBeforeDiscount,amounts.discountAmount,amounts.shippingAmount,amounts.finalAmount,estimatedMinutes,printerAssignment,productionWindow).run();
  await logCustomEvent(db,ids.orderId,'CUSTOM_ORDER_CREATED',{customerId:customer.id,title,finalAmount:amounts.finalAmount,productionRequired});return getCustomOrderDetail(env,ids.orderId);
}

export async function repeatCustomOrder(env,orderId){const source=await getCustomOrderDetail(env,orderId);return createCustomOrder(env,{customerId:source.customerId,title:source.title,lineItems:source.lineItems,customerNote:source.customerNote,adminNotes:`Repeated from ${source.orderId}`,fulfillmentMethod:source.fulfillmentMethod,paymentRequired:source.paymentRequired,productionRequired:source.productionRequired,discountAmount:source.discountAmount,shippingAmount:source.shippingAmount,estimatedPrinterMinutes:source.estimatedPrinterMinutes,printerAssignment:source.printerAssignment,productionWindow:source.productionWindow});}
export function isCustomOrderLocked(order){return String(order?.paymentStatus||'').toUpperCase()==='PAID'||PRODUCTION_STATUSES.has(String(order?.status||'').toUpperCase());}
export function areCustomTermsFrozen(order){if(isCustomOrderLocked(order))return true;const status=String(order?.status||'').toUpperCase();if(status==='CHANGES_REQUESTED')return false;return FROZEN_STATUSES.has(status);}
function assertForward(order,status){const current=String(order.status||'').toUpperCase(),configured=FORWARD_STATUS[current],next=typeof configured==='string'?configured:configured?.[order.fulfillmentMethod];if(status!==current&&status!==next)throw makeError(next?`Order status can only remain ${current} or move forward to ${next}.`:`Order status cannot move backward from ${current}.`,409);}

export async function updateCustomOrderAdmin(env,orderId,body={}){
  const db=requireOrdersDb(env),current=await getCustomOrderDetail(env,orderId),action=clean(body?.action,40)||'saveOrder';
  if(action==='addWork'){if(current.status==='ARCHIVED')throw makeError('Restore the archived order before adding work.',409);const minutes=integer(body?.minutes,0,1000000),workType=clean(body?.workType,80)||'CUSTOM_WORK',note=clean(body?.note,1200);if(!minutes&&!note)throw makeError('Add minutes or a work note.');await db.prepare(`INSERT INTO custom_order_work_log (order_id,work_type,minutes,note) VALUES (?,?,?,?)`).bind(current.orderId,workType,minutes,note).run();await logCustomEvent(db,current.orderId,'WORK_LOGGED',{workType,minutes,note});return getCustomOrderDetail(env,current.orderId);}
  if(action==='archive'){if(current.status!=='COMPLETED')throw makeError('Only completed orders can be archived.',409);await db.prepare(`UPDATE custom_orders SET status='ARCHIVED',archived_at=?,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(nowIso(),current.orderId).run();await logCustomEvent(db,current.orderId,'ORDER_ARCHIVED',{previousStatus:'COMPLETED'});const updated=await getCustomOrderDetail(env,current.orderId);await syncManufacturingWorkOrder(env,'CUSTOM',updated);return updated;}
  if(action==='restoreArchive'){if(current.status!=='ARCHIVED')throw makeError('Only archived orders can be restored.',409);await db.prepare(`UPDATE custom_orders SET status='COMPLETED',archived_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(current.orderId).run();await logCustomEvent(db,current.orderId,'ORDER_RESTORED',{status:'COMPLETED'});const updated=await getCustomOrderDetail(env,current.orderId);await syncManufacturingWorkOrder(env,'CUSTOM',updated);return updated;}
  if(current.status==='ARCHIVED')throw makeError('Restore the archived order before changing it.',409);
  if(action!=='saveOrder')throw makeError('Unsupported custom order action.');
  if(isCustomOrderLocked(current)){
    const status=(clean(body?.status,40)||current.status).toUpperCase();if(!PRODUCTION_STATUSES.has(status))throw makeError('Paid custom orders can only use production statuses.',409);assertForward(current,status);if(['PREPARING_FOR_PICKUP','READY_FOR_PICKUP'].includes(status)&&current.fulfillmentMethod!=='LOCAL_PICKUP')throw makeError('That status is only valid for Local Pickup orders.');if(['PREPARING_TO_SHIP','SHIPPED'].includes(status)&&current.fulfillmentMethod!=='SHIP')throw makeError('That status is only valid for shipped orders.');const suppliedCarrier=clean(body?.trackingCarrier,100),carrier=normalizeCarrier(suppliedCarrier),tracking=clean(body?.trackingNumber,180);if(suppliedCarrier&&!carrier)throw makeError('Choose USPS, UPS, FedEx, or DHL.');if(status==='SHIPPED'&&(!carrier||!tracking))throw makeError('Choose a carrier and enter tracking before marking Shipped.');const when=nowIso();await db.prepare(`UPDATE custom_orders SET status=?,admin_notes=?,printer_assignment=?,tracking_carrier=?,tracking_number=?,pickup_ready_at=CASE WHEN ?='READY_FOR_PICKUP' THEN COALESCE(pickup_ready_at,?) ELSE pickup_ready_at END,shipped_at=CASE WHEN ?='SHIPPED' THEN COALESCE(shipped_at,?) ELSE shipped_at END,completed_at=CASE WHEN ?='COMPLETED' THEN COALESCE(completed_at,?) ELSE completed_at END,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(status,clean(body?.adminNotes,5000),normalizePrinter(body?.printerAssignment),carrier||null,tracking||null,status,when,status,when,status,when,current.orderId).run();await logCustomEvent(db,current.orderId,'PRODUCTION_UPDATED',{previousStatus:current.status,status,trackingCarrier:carrier,trackingNumber:tracking});const updated=await getCustomOrderDetail(env,current.orderId);await syncManufacturingWorkOrder(env,'CUSTOM',updated);updated._statusChanged=current.status!==status;return updated;
  }
  if(areCustomTermsFrozen(current)){await db.prepare(`UPDATE custom_orders SET admin_notes=?,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(clean(body?.adminNotes,5000),current.orderId).run();await logCustomEvent(db,current.orderId,'INTERNAL_NOTE_UPDATED',{customerTermsLocked:true});return getCustomOrderDetail(env,current.orderId);}
  const customer=await getCustomCustomer(env,body?.customerId||current.customerId);if(!customer)throw makeError('Choose a customer.');const status=(clean(body?.status,40)||current.status).toUpperCase();if(!REVIEW_STATUSES.has(status))throw makeError('Choose a valid draft status.');const fulfillment=(clean(body?.fulfillmentMethod,30)||current.fulfillmentMethod).toUpperCase();if(!FULFILLMENT_METHODS.has(fulfillment))throw makeError('Choose a valid fulfillment method.');const items=normalizeCustomLineItems(body?.lineItems,{required:true}),shipping=fulfillment==='LOCAL_PICKUP'?0:money(body?.shippingAmount),amounts=calculateCustomAmounts(items,body?.discountAmount,shipping),title=clean(body?.title,200),productionRequired=body?.productionRequired!==false,estimatedMinutes=productionRequired?integer(body?.estimatedPrinterMinutes,1,1000000):0,printerAssignment=productionRequired?normalizePrinter(body?.printerAssignment):'UNASSIGNED',productionWindow=productionRequired?(clean(body?.productionWindow,160)||null):null;if(title.length<2)throw makeError('Enter an order title.');
  await db.prepare(`UPDATE custom_orders SET customer_id=?,status=?,customer_name=?,customer_email=?,customer_phone=?,title=?,line_items_json=?,customer_note=?,admin_notes=?,fulfillment_method=?,payment_required=?,production_required=?,subtotal_amount=?,taxable_amount_before_discount=?,discount_amount=?,shipping_amount=?,final_amount=?,estimated_printer_minutes=?,printer_assignment=?,production_window=?,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(customer.id,status,customer.displayName,customer.email,customer.phone||null,title,json(amounts.items),clean(body?.customerNote,3000)||null,clean(body?.adminNotes,5000)||null,fulfillment,body?.paymentRequired===false?0:1,productionRequired?1:0,amounts.subtotalAmount,amounts.taxableAmountBeforeDiscount,amounts.discountAmount,amounts.shippingAmount,amounts.finalAmount,estimatedMinutes,printerAssignment,productionWindow,current.orderId).run();await logCustomEvent(db,current.orderId,'CUSTOM_ORDER_SAVED',{status,customerId:customer.id,finalAmount:amounts.finalAmount,paymentRequired:body?.paymentRequired!==false,productionRequired});return getCustomOrderDetail(env,current.orderId);
}

export async function releaseCustomOrder(env,orderId,{refreshOnly=false}={}){
  const db=requireOrdersDb(env),order=await getCustomOrderDetail(env,orderId),status=String(order.status||'').toUpperCase();if(isCustomOrderLocked(order)||['ORDER_APPROVED','AWAITING_PAYMENT'].includes(status))throw makeError('Approved custom order terms are locked.',409);
  if(refreshOnly){if(status!=='ORDER_SENT'||!order.orderVersion||!order.orderSentAt)throw makeError('Only an order awaiting customer approval can receive a refreshed link.',409);const token=newToken(),hash=await sha256(token),expires=tokenExpiry(),sent=nowIso();await db.prepare(`UPDATE custom_orders SET approval_token_hash=?,approval_expires_at=?,order_sent_at=?,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(hash,expires,sent,order.orderId).run();await logCustomEvent(db,order.orderId,'APPROVAL_LINK_REFRESHED',{orderVersion:order.orderVersion});return {order:await getCustomOrderDetail(env,order.orderId),approvalToken:token};}
  if(!['SHIP','LOCAL_PICKUP'].includes(order.fulfillmentMethod))throw makeError('Choose Ship Order or Local Pickup before sending the order.',409);normalizeCustomLineItems(order.lineItems,{required:true});if(order.productionRequired&&Number(order.estimatedPrinterMinutes||0)<=0)throw makeError('Enter estimated printer minutes before sending the order.',409);if(order.productionRequired&&!clean(order.productionWindow,160))throw makeError('Enter the estimated production window before sending the order.',409);if(order.paymentRequired&&money(order.finalAmount)<=0)throw makeError('Set an amount due, or turn Payment Required off.',409);if(order.paymentRequired&&money(order.subtotalAmount-order.discountAmount)<=0)throw makeError('PayPal requires a positive item subtotal. Add a priced line item or turn Payment Required off.',409);
  const token=newToken(),hash=await sha256(token),expires=tokenExpiry(),sent=nowIso(),version=Math.max(0,Number(order.orderVersion||0))+1;
  await db.prepare(`UPDATE custom_orders SET order_version=?,approval_token_hash=?,approval_expires_at=?,order_sent_at=?,order_approved_at=NULL,changes_requested_at=NULL,customer_change_request=NULL,payment_status='NOT_REQUESTED',paypal_order_id=NULL,paypal_approval_url=NULL,paypal_order_status=NULL,paypal_capture_id=NULL,paypal_paid_at=NULL,paypal_last_error=NULL,taxable_amount=0,tax_amount=0,tax_rate=0,tax_jurisdiction_code=NULL,tax_source=NULL,tax_address_source=NULL,tax_address_json=NULL,tax_quote_json=NULL,payment_total=0,tax_prepared_at=NULL,tax_confirmed_at=NULL,status='ORDER_SENT',updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(version,hash,expires,sent,order.orderId).run();await logCustomEvent(db,order.orderId,'CUSTOM_ORDER_SENT',{orderVersion:version,finalAmount:order.finalAmount,productionRequired:order.productionRequired,productionWindow:order.productionWindow});return {order:await getCustomOrderDetail(env,order.orderId),approvalToken:token};
}

export function customApprovalView(order){if(!order)return null;return {orderId:order.orderId,status:order.status,customerName:order.customerName,title:order.title,lineItems:order.lineItems,customerNote:order.customerNote,fulfillmentMethod:order.fulfillmentMethod,paymentRequired:order.paymentRequired,productionRequired:order.productionRequired,subtotalAmount:order.subtotalAmount,taxableAmountBeforeDiscount:order.taxableAmountBeforeDiscount,discountAmount:order.discountAmount,shippingAmount:order.shippingAmount,finalAmount:order.finalAmount,productionWindow:order.productionWindow,orderVersion:order.orderVersion,orderSentAt:order.orderSentAt,orderApprovedAt:order.orderApprovedAt,customerChangeRequest:order.customerChangeRequest,paymentStatus:order.paymentStatus,paypalOrderId:order.paypalOrderId,paypalApprovalUrl:order.paypalApprovalUrl,paypalOrderStatus:order.paypalOrderStatus,paypalPaidAt:order.paypalPaidAt,taxableAmount:order.taxableAmount,taxAmount:order.taxAmount,taxRate:order.taxRate,taxJurisdictionCode:order.taxJurisdictionCode,taxSource:order.taxSource,taxAddressSource:order.taxAddressSource,taxAddressJson:order.taxAddressJson,paymentTotal:order.paymentTotal,taxPreparedAt:order.taxPreparedAt,taxConfirmedAt:order.taxConfirmedAt,trackingCarrier:order.trackingCarrier,trackingNumber:order.trackingNumber};}
export async function getCustomApprovalByToken(env,orderId,token){const db=requireOrdersDb(env),hash=await sha256(clean(token,200)),row=await db.prepare(`SELECT order_id FROM custom_orders WHERE order_id=? AND approval_token_hash=? AND datetime(approval_expires_at)>CURRENT_TIMESTAMP LIMIT 1`).bind(clean(orderId,80),hash).first();if(!row)return null;return customApprovalView(await getCustomOrderDetail(env,row.order_id));}
export async function recordCustomApprovalAction(env,orderId,token,action,message=''){
  const db=requireOrdersDb(env),approval=await getCustomApprovalByToken(env,orderId,token);if(!approval)throw makeError('This approval link is invalid or expired.',404);const current=await getCustomOrderDetail(env,orderId);if(isCustomOrderLocked(current))throw makeError('This order is already queued or in production and is locked.',409);
  if(action==='requestChanges'){if(current.status!=='ORDER_SENT')throw makeError('This order is no longer awaiting a decision.',409);const note=clean(message,2500);if(note.length<2)throw makeError('Tell WestTech what you would like changed.');await db.prepare(`UPDATE custom_orders SET status='CHANGES_REQUESTED',payment_status='NOT_REQUESTED',customer_change_request=?,changes_requested_at=?,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(note,nowIso(),current.orderId).run();await logCustomEvent(db,current.orderId,'CUSTOMER_CHANGES_REQUESTED',{orderVersion:current.orderVersion,message:note});return getCustomOrderDetail(env,current.orderId);}
  if(action!=='approve')throw makeError('Unsupported approval action.');if(['ORDER_APPROVED','AWAITING_PAYMENT'].includes(current.status)&&current.paymentStatus!=='PAID')return current;if(current.status!=='ORDER_SENT')throw makeError('This order is no longer awaiting approval.',409);await db.prepare(`UPDATE custom_orders SET status='ORDER_APPROVED',order_approved_at=?,customer_change_request=NULL,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(nowIso(),current.orderId).run();await logCustomEvent(db,current.orderId,'CUSTOMER_ORDER_APPROVED',{orderVersion:current.orderVersion,finalAmount:current.finalAmount,productionWindow:current.productionWindow});return getCustomOrderDetail(env,current.orderId);
}
