import { generateAccessToken, paypalBaseUrl } from './paypal.js';
import { buildTaxQuote } from './tax.js';
import { ensureManufacturingWorkOrder } from './manufacturing-work-orders.js';
import { requireOrdersDb } from './orders.js';
import { readJsonSafe, sanitizeEnvValue } from './shared.js';
import { clean, getCustomApprovalByToken, getCustomOrderDetail, money } from './custom-orders.js';
import { sendCustomCustomerEmail } from './custom-email.js';

const PICKUP_ADDRESS={fullName:'WestTech Home Automation, LLC',address1:'11300 Emporia St',address2:'',city:'Henderson',state:'CO',postalCode:'80640',countryCode:'US'};
function usd(value){return money(value).toFixed(2);}
function approvalUrl(data){return clean(data?.links?.find?.(link=>['payer-action','approve'].includes(String(link?.rel||'').toLowerCase()))?.href||'',2000);}
function captureId(data){return clean(data?.purchase_units?.[0]?.payments?.captures?.[0]?.id||'',120);}
function extractShipping(data){const shipping=data?.purchase_units?.[0]?.shipping||{},payer=data?.payer?.name||{};return {name:shipping?.name?.full_name||[payer.given_name,payer.surname].filter(Boolean).join(' '),address1:shipping?.address?.address_line_1||'',address2:shipping?.address?.address_line_2||'',city:shipping?.address?.admin_area_2||'',region:shipping?.address?.admin_area_1||'',postalCode:shipping?.address?.postal_code||'',country:shipping?.address?.country_code||''};}
function requireUsShipping(address){if(String(address?.country||'').toUpperCase()!=='US')throw Object.assign(new Error('Website checkout currently supports U.S. shipping addresses only.'),{status:400});if(!clean(address?.address1)||!clean(address?.city)||!clean(address?.region)||!clean(address?.postalCode))throw Object.assign(new Error('PayPal did not provide a complete shipping address.'),{status:400});}
async function paypalCall(env,path,{method='GET',body,accessToken,requestId}={}){const token=accessToken||await generateAccessToken(env),headers={Authorization:`Bearer ${token}`,Accept:'application/json'};if(body!==undefined)headers['Content-Type']='application/json';if(requestId)headers['PayPal-Request-Id']=requestId;const response=await fetch(`${paypalBaseUrl(env.PAYPAL_ENV)}${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),data=await readJsonSafe(response);if(!response.ok){const error=new Error(data?.details?.[0]?.description||data?.message||data?.error_description||data?.raw||`PayPal request failed (${response.status}).`);error.status=response.status||500;error.paypal=data;throw error;}return {data,accessToken:token};}
function requestId(orderId,version,action){return `${String(orderId).replace(/[^A-Za-z0-9_-]/g,'-')}-O${Number(version||0)}-${action}`.slice(0,100);}
function customAmounts(order){const subtotal=money(order.subtotalAmount),discount=Math.min(subtotal,money(order.discountAmount)),itemAmount=money(subtotal-discount),taxableBefore=money(order.taxableAmountBeforeDiscount),ratio=subtotal>0?taxableBefore/subtotal:0,taxableAmount=money(Math.max(0,taxableBefore-(discount*ratio))),shippingAmount=money(order.shippingAmount);return {itemAmount,taxableAmount,shippingAmount,approvedTotal:money(itemAmount+shippingAmount)};}
function paidStatus(order){if(order?.productionRequired!==false)return 'PRODUCTION_QUEUE';return order?.fulfillmentMethod==='LOCAL_PICKUP'?'READY_FOR_PICKUP':'PREPARING_TO_SHIP';}
function paidEmailType(order){return order?.productionRequired===false?paidStatus(order):'PRODUCTION_QUEUED';}
function paypalItem(order,currency,itemAmount){return {name:clean(order.title,120)||'WestTech Custom Order',description:`Custom work order ${order.orderId} • Version ${Math.max(1,Number(order.orderVersion||1))}`,quantity:'1',unit_amount:{currency_code:currency,value:usd(itemAmount)},category:'PHYSICAL_GOODS'};}
function amountBreakdown(currency,itemAmount,shippingAmount,taxAmount=0){return {currency_code:currency,value:usd(money(itemAmount)+money(shippingAmount)+money(taxAmount)),breakdown:{item_total:{currency_code:currency,value:usd(itemAmount)},shipping:{currency_code:currency,value:usd(shippingAmount)},tax_total:{currency_code:currency,value:usd(taxAmount)}}};}
function buildPayload(order,currency,{returnUrl,cancelUrl}){const amounts=customAmounts(order),shippingPreference=order.fulfillmentMethod==='SHIP'?'GET_FROM_FILE':'NO_SHIPPING';return {intent:'CAPTURE',purchase_units:[{reference_id:'CUSTOM_ORDER',custom_id:order.orderId,invoice_id:`${order.orderId}-O${Math.max(1,Number(order.orderVersion||1))}`,description:`${clean(order.title,180)} • ${order.orderId}`,amount:amountBreakdown(currency,amounts.itemAmount,amounts.shippingAmount),items:[paypalItem(order,currency,amounts.itemAmount)]}],payment_source:{paypal:{experience_context:{shipping_preference:shippingPreference,user_action:'PAY_NOW',return_url:returnUrl,cancel_url:cancelUrl}}}};}
function taxAddressFor(order,details){if(order.fulfillmentMethod==='LOCAL_PICKUP')return {...PICKUP_ADDRESS};const ship=extractShipping(details);requireUsShipping(ship);return {fullName:ship.name,address1:ship.address1,address2:ship.address2,city:ship.city,state:ship.region,postalCode:ship.postalCode,countryCode:ship.country};}
function addressJson(address){return JSON.stringify({fullName:clean(address?.fullName,200),address1:clean(address?.address1,200),address2:clean(address?.address2,200),city:clean(address?.city,120),state:clean(address?.state,20).toUpperCase(),postalCode:clean(address?.postalCode,30),countryCode:clean(address?.countryCode,10).toUpperCase()});}
function taxConfirmationMatches(order,quote){return !!(quote?.isColorado&&order?.taxConfirmedAt&&order.taxAddressJson===addressJson(quote.address)&&Math.abs(money(order.taxAmount)-money(quote.taxAmount))<0.001&&Math.abs(money(order.paymentTotal)-money(quote.totalAmount))<0.001);}
async function persistTaxQuote(env,order,quote,addressSource,confirmTax){const db=requireOrdersDb(env),now=new Date().toISOString(),address=addressJson(quote.address),quoteJson=JSON.stringify(quote),wasConfirmed=taxConfirmationMatches(order,quote),unchanged=order.taxAddressJson===address&&Math.abs(money(order.taxAmount)-money(quote.taxAmount))<0.001&&Math.abs(money(order.paymentTotal)-money(quote.totalAmount))<0.001;
  await db.prepare(`UPDATE custom_orders SET taxable_amount=?,tax_amount=?,tax_rate=?,tax_jurisdiction_code=?,tax_source=?,tax_address_source=?,tax_address_json=?,tax_quote_json=?,payment_total=?,tax_prepared_at=?,tax_confirmed_at=CASE WHEN ?=1 THEN ? WHEN tax_address_json=? AND ABS(COALESCE(tax_amount,0)-?)<0.001 AND ABS(COALESCE(payment_total,0)-?)<0.001 THEN tax_confirmed_at ELSE NULL END,payment_status=CASE WHEN payment_status='PAID' THEN 'PAID' WHEN ?=1 AND ?=0 THEN 'AWAITING_TAX_CONFIRMATION' ELSE 'AWAITING_PAYMENT' END,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(Number(quote.taxableAmount),Number(quote.taxAmount),Number(quote.taxRate),clean(quote.jurisdictionCode,200)||null,clean(quote.source,80)||null,addressSource,address,quoteJson,Number(quote.totalAmount),now,confirmTax?1:0,now,address,Number(quote.taxAmount),Number(quote.totalAmount),quote.isColorado?1:0,confirmTax||wasConfirmed?1:0,order.orderId).run();
  if(!unchanged)await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,'TAX_PREPARED',?)`).bind(order.orderId,JSON.stringify({source:quote.source,addressSource,isColorado:quote.isColorado,taxRate:quote.taxRate,taxAmount:Number(quote.taxAmount),paymentTotal:Number(quote.totalAmount),jurisdictionCode:quote.jurisdictionCode||null})).run();
  if(quote.isColorado&&confirmTax&&!wasConfirmed)await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,'COLORADO_TAX_CONFIRMED',?)`).bind(order.orderId,JSON.stringify({addressSource,taxAmount:Number(quote.taxAmount),paymentTotal:Number(quote.totalAmount),jurisdictionCode:quote.jurisdictionCode||null})).run();
  return getCustomOrderDetail(env,order.orderId);
}
function taxPatch(order,quote,currency){const amounts=customAmounts(order);return [{op:'replace',path:"/purchase_units/@reference_id=='CUSTOM_ORDER'/amount",value:amountBreakdown(currency,Number(quote.itemAmount),Number(quote.shippingAmount),Number(quote.taxAmount))},{op:'replace',path:"/purchase_units/@reference_id=='CUSTOM_ORDER'/items",value:[paypalItem(order,currency,amounts.itemAmount)]}];}
async function preparePayPalTax(env,order,details,accessToken,{confirmTax=false}={}){const address=taxAddressFor(order,details),amounts=customAmounts(order),quote=await buildTaxQuote(env,address,{taxableAmount:amounts.taxableAmount,itemAmount:amounts.itemAmount,shippingAmount:amounts.shippingAmount}),currency=sanitizeEnvValue(env.PAYPAL_CURRENCY)||'USD';await paypalCall(env,`/v2/checkout/orders/${encodeURIComponent(order.paypalOrderId)}`,{method:'PATCH',body:taxPatch(order,quote,currency),accessToken});const confirmationAccepted=!quote.isColorado||confirmTax||taxConfirmationMatches(order,quote),updated=await persistTaxQuote(env,order,quote,order.fulfillmentMethod==='LOCAL_PICKUP'?'WESTTECH_PICKUP':'PAYPAL',quote.isColorado&&confirmationAccepted);return {order:updated,quote,address:quote.address,addressSource:order.fulfillmentMethod==='LOCAL_PICKUP'?'WESTTECH_PICKUP':'PAYPAL',confirmationAccepted};}
function taxReview(prepared){return {address:prepared.address,addressSource:prepared.addressSource,fulfillmentMethod:prepared.order.fulfillmentMethod,taxRate:Number(prepared.quote.taxRate),taxableAmount:Number(prepared.quote.taxableAmount),itemAmount:Number(prepared.quote.itemAmount),shippingAmount:Number(prepared.quote.shippingAmount),taxAmount:Number(prepared.quote.taxAmount),totalAmount:Number(prepared.quote.totalAmount),jurisdictionCode:prepared.quote.jurisdictionCode||''};}

export async function recordCustomPayPalFailure(env,orderId,error){const db=requireOrdersDb(env),message=clean(error?.message||'PayPal checkout setup failed.',1000);await db.prepare(`UPDATE custom_orders SET payment_status='PAYPAL_ERROR',paypal_last_error=?,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(message,orderId).run();await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,'PAYPAL_ERROR',?)`).bind(orderId,JSON.stringify({message})).run();return getCustomOrderDetail(env,orderId);}
export async function ensureCustomPayPalOrder(env,orderId,{returnUrl,cancelUrl}={}){
  const db=requireOrdersDb(env);let order=await getCustomOrderDetail(env,orderId);if(order.paymentStatus==='PAID'){await ensureManufacturingWorkOrder(env,'CUSTOM',order);return order;}
  if(order.paymentRequired===false){if(order.paymentStatus==='NOT_REQUIRED'){await ensureManufacturingWorkOrder(env,'CUSTOM',order);return order;}const status=paidStatus(order),readyAt=status==='READY_FOR_PICKUP'?new Date().toISOString():null;await db.prepare(`UPDATE custom_orders SET payment_status='NOT_REQUIRED',status=?,pickup_ready_at=CASE WHEN ? IS NOT NULL THEN COALESCE(pickup_ready_at,?) ELSE pickup_ready_at END,paypal_last_error=NULL,payment_total=0,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(status,readyAt,readyAt,orderId).run();await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,'PAYMENT_NOT_REQUIRED',?)`).bind(orderId,JSON.stringify({finalAmount:money(order.finalAmount)})).run();const eventType=order.productionRequired===false?'FULFILLMENT_READY':'PRODUCTION_QUEUED';await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,?,?)`).bind(orderId,eventType,JSON.stringify({reason:'NO_PAYMENT_REQUIRED',status,productionRequired:order.productionRequired})).run();const queued=await getCustomOrderDetail(env,orderId);await ensureManufacturingWorkOrder(env,'CUSTOM',queued);await sendCustomCustomerEmail(env,{type:paidEmailType(queued),order:queued});return queued;}
  if(order.status!=='ORDER_APPROVED')throw Object.assign(new Error('Customer approval is required before PayPal checkout can be created.'),{status:409});const amounts=customAmounts(order);if(amounts.itemAmount<=0)throw Object.assign(new Error('The approved item subtotal must be greater than $0 before PayPal checkout can be created.'),{status:400});if(!returnUrl||!cancelUrl)throw Object.assign(new Error('PayPal return and cancel URLs are required.'),{status:500});
  if(order.paypalOrderId){const got=await paypalCall(env,`/v2/checkout/orders/${encodeURIComponent(order.paypalOrderId)}`),url=approvalUrl(got.data);await db.prepare(`UPDATE custom_orders SET paypal_order_status=?,paypal_approval_url=CASE WHEN ?<>'' THEN ? ELSE paypal_approval_url END,payment_status=CASE WHEN payment_status='PAID' THEN payment_status ELSE 'AWAITING_PAYMENT' END,status=CASE WHEN payment_status='PAID' THEN status ELSE 'AWAITING_PAYMENT' END,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(String(got.data?.status||''),url,url,orderId).run();return getCustomOrderDetail(env,orderId);}
  const currency=sanitizeEnvValue(env.PAYPAL_CURRENCY)||'USD',token=await generateAccessToken(env),payload=buildPayload(order,currency,{returnUrl,cancelUrl});await db.prepare(`UPDATE custom_orders SET payment_status='CREATING_PAYPAL_ORDER',paypal_last_error=NULL,taxable_amount=0,tax_amount=0,tax_rate=0,tax_jurisdiction_code=NULL,tax_source=NULL,tax_address_source=NULL,tax_address_json=NULL,tax_quote_json=NULL,payment_total=0,tax_prepared_at=NULL,tax_confirmed_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(orderId).run();const created=await paypalCall(env,'/v2/checkout/orders',{method:'POST',body:payload,accessToken:token,requestId:requestId(order.orderId,order.orderVersion,'create-order')});if(!created.data?.id)throw new Error('PayPal created the checkout but did not return an order ID.');const url=approvalUrl(created.data);await db.prepare(`UPDATE custom_orders SET paypal_order_id=?,paypal_order_status=?,paypal_approval_url=?,payment_status='AWAITING_PAYMENT',status='AWAITING_PAYMENT',updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(created.data.id,String(created.data.status||'CREATED'),url||null,orderId).run();await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,'PAYPAL_ORDER_CREATED',?)`).bind(orderId,JSON.stringify({paypalOrderId:created.data.id,approvedSubtotal:money(order.finalAmount),shippingPreference:order.fulfillmentMethod==='SHIP'?'GET_FROM_FILE':'NO_SHIPPING',taxTiming:'AFTER_PAYPAL_ADDRESS'})).run();return getCustomOrderDetail(env,orderId);
}

async function markCaptured(env,orderId,paypalOrderId,details,captured){
  const db=requireOrdersDb(env),order=await getCustomOrderDetail(env,orderId);if(order.paymentStatus==='PAID'){await ensureManufacturingWorkOrder(env,'CUSTOM',order);order._paymentCapturedNow=false;return order;}
  const capturedShip=extractShipping(captured),detailShip=extractShipping(details),ship=order.fulfillmentMethod==='SHIP'?(capturedShip.address1?capturedShip:detailShip):null;if(order.fulfillmentMethod==='SHIP')requireUsShipping(ship);
  const capture=captureId(captured)||captureId(details),paidAt=new Date().toISOString(),status=paidStatus(order),write=await db.prepare(`UPDATE custom_orders SET paypal_order_status='COMPLETED',paypal_capture_id=?,payment_status='PAID',paypal_paid_at=COALESCE(paypal_paid_at,?),paypal_last_error=NULL,status=?,pickup_ready_at=CASE WHEN ?='READY_FOR_PICKUP' THEN COALESCE(pickup_ready_at,?) ELSE pickup_ready_at END,shipping_name=?,shipping_address1=?,shipping_address2=?,shipping_city=?,shipping_region=?,shipping_postal_code=?,shipping_country=?,payment_total=CASE WHEN payment_total>0 THEN payment_total ELSE final_amount END,updated_at=CURRENT_TIMESTAMP WHERE order_id=? AND COALESCE(payment_status,'')<>'PAID'`).bind(capture||null,paidAt,status,status,paidAt,ship?.name||null,ship?.address1||null,ship?.address2||null,ship?.city||null,ship?.region||null,ship?.postalCode||null,ship?.country||null,orderId).run();
  if(!Number(write?.meta?.changes||0)){const existing=await getCustomOrderDetail(env,orderId);existing._paymentCapturedNow=false;return existing;}
  const paid=await getCustomOrderDetail(env,orderId);await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,'PAYPAL_ORDER_CAPTURED',?)`).bind(orderId,JSON.stringify({paypalOrderId,captureId:capture||null,paymentStatus:'PAID',approvedSubtotal:money(paid.finalAmount),taxAmount:money(paid.taxAmount),paymentTotal:money(paid.paymentTotal),addressSource:ship?'PAYPAL':'WESTTECH_PICKUP'})).run();
  const eventType=paid.productionRequired===false?'FULFILLMENT_READY':'PRODUCTION_QUEUED';await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,?,?)`).bind(orderId,eventType,JSON.stringify({reason:'PAYMENT_RECEIVED',status:paid.status,productionRequired:paid.productionRequired,paypalOrderId,captureId:capture||null})).run();
  const queued=await getCustomOrderDetail(env,orderId);await ensureManufacturingWorkOrder(env,'CUSTOM',queued);await sendCustomCustomerEmail(env,{type:paidEmailType(queued),order:queued});queued._paymentCapturedNow=true;return queued;
}
export async function captureCustomPayPalOrder(env,orderId,approvalToken,paypalOrderId,{confirmTax=false}={}){const approval=await getCustomApprovalByToken(env,orderId,approvalToken);if(!approval)throw Object.assign(new Error('This approval link is invalid.'),{status:404});const order=await getCustomOrderDetail(env,orderId);if(!order.paypalOrderId||order.paypalOrderId!==paypalOrderId)throw Object.assign(new Error('This PayPal checkout does not match the approved custom order.'),{status:409});if(order.paymentStatus==='PAID'){await ensureManufacturingWorkOrder(env,'CUSTOM',order);return {order,capturedNow:false,taxConfirmationRequired:false};}let accessToken=await generateAccessToken(env),detail=await paypalCall(env,`/v2/checkout/orders/${encodeURIComponent(paypalOrderId)}`,{accessToken});accessToken=detail.accessToken;const status=String(detail.data?.status||'').toUpperCase();if(!['APPROVED','COMPLETED'].includes(status))throw Object.assign(new Error(`PayPal checkout is not ready to capture (status: ${status||'UNKNOWN'}).`),{status:409});if(status==='COMPLETED'){const paid=await markCaptured(env,orderId,paypalOrderId,detail.data,detail.data);return {order:paid,capturedNow:!!paid?._paymentCapturedNow,taxConfirmationRequired:false};}const prepared=await preparePayPalTax(env,order,detail.data,accessToken,{confirmTax});if(prepared.quote.isColorado&&!prepared.confirmationAccepted)return {order:prepared.order,capturedNow:false,taxConfirmationRequired:true,taxReview:taxReview(prepared)};const captured=await paypalCall(env,`/v2/checkout/orders/${encodeURIComponent(paypalOrderId)}/capture`,{method:'POST',body:{},accessToken,requestId:requestId(order.orderId,order.orderVersion,'capture')}),paid=await markCaptured(env,orderId,paypalOrderId,detail.data,captured.data);return {order:paid,capturedNow:!!paid?._paymentCapturedNow,taxConfirmationRequired:false};}
export async function syncCustomPayPalOrder(env,orderId){const db=requireOrdersDb(env),order=await getCustomOrderDetail(env,orderId);if(order.paymentStatus==='PAID'){await ensureManufacturingWorkOrder(env,'CUSTOM',order);return order;}if(!order.paypalOrderId)throw Object.assign(new Error('No PayPal checkout exists for this order yet.'),{status:404});let accessToken=await generateAccessToken(env),got=await paypalCall(env,`/v2/checkout/orders/${encodeURIComponent(order.paypalOrderId)}`,{accessToken});accessToken=got.accessToken;const status=String(got.data?.status||'').toUpperCase(),url=approvalUrl(got.data);await db.prepare(`UPDATE custom_orders SET paypal_order_status=?,paypal_approval_url=CASE WHEN ?<>'' THEN ? ELSE paypal_approval_url END,updated_at=CURRENT_TIMESTAMP WHERE order_id=?`).bind(status,url,url,orderId).run();if(status==='COMPLETED')return markCaptured(env,orderId,order.paypalOrderId,got.data,got.data);if(status==='APPROVED'){const prepared=await preparePayPalTax(env,order,got.data,accessToken);if(prepared.quote.isColorado&&!prepared.confirmationAccepted)throw Object.assign(new Error('The customer must confirm the Colorado tax total on the order page before this payment can be captured.'),{status:409});const captured=await paypalCall(env,`/v2/checkout/orders/${encodeURIComponent(order.paypalOrderId)}/capture`,{method:'POST',body:{},accessToken,requestId:requestId(order.orderId,order.orderVersion,'capture')});return markCaptured(env,orderId,order.paypalOrderId,got.data,captured.data);}await db.prepare(`INSERT INTO custom_order_events (order_id,event_type,detail) VALUES (?,'PAYPAL_STATUS_SYNCED',?)`).bind(orderId,JSON.stringify({paypalOrderId:order.paypalOrderId,paypalStatus:status})).run();return getCustomOrderDetail(env,orderId);}
