import { customApprovalView, getCustomApprovalByToken, getCustomOrderDetail, recordCustomApprovalAction, recordCustomOrderView } from '../../../../_lib/custom-orders.js';
import { sendCustomAdminChangeRequestEmail, sendCustomAdminProductionEmail, sendCustomCustomerEmail } from '../../../../_lib/custom-email.js';
import { ensureCustomPayPalOrder, recordCustomPayPalFailure } from '../../../../_lib/custom-paypal.js';
import { jsonResponse } from '../../../../_lib/shared.js';

function orderPage(request,orderId,token){const url=new URL(request.url);return `${url.protocol}//${url.host}/custom-orders/order-approval.html?order=${encodeURIComponent(orderId)}&approvalToken=${encodeURIComponent(token)}`;}
export async function onRequestGet(context){try{const token=new URL(context.request.url).searchParams.get('approvalToken')||'',approval=await getCustomApprovalByToken(context.env,context.params.orderId,token);if(!approval)return jsonResponse({ok:false,message:'This custom order link is invalid or expired.'},404);await recordCustomOrderView(context.env,approval.orderId,approval.orderVersion).catch(()=>{});return jsonResponse({ok:true,approval});}catch(error){return jsonResponse({ok:false,message:error.message||'Could not load custom order.'},error.status||500);}}
export async function onRequestPost(context){try{const body=await context.request.json(),token=String(body?.approvalToken||''),action=String(body?.action||''),orderId=context.params.orderId;let order=await recordCustomApprovalAction(context.env,orderId,token,action,body?.message||''),paymentWarning='';if(action==='requestChanges'){await Promise.all([sendCustomCustomerEmail(context.env,{type:'CHANGES_REQUESTED',order,requestUrl:context.request.url}),sendCustomAdminChangeRequestEmail(context.env,{order,requestUrl:context.request.url})]);}else if(action==='approve'){const page=orderPage(context.request,order.orderId,token);try{order=await ensureCustomPayPalOrder(context.env,order.orderId,{returnUrl:`${page}&payment=return`,cancelUrl:`${page}&payment=cancel`});if(order.paymentRequired)await sendCustomCustomerEmail(context.env,{type:'PAYMENT_REQUIRED',order,approvalUrl:page,requestUrl:context.request.url});else await sendCustomAdminProductionEmail(context.env,{order,requestUrl:context.request.url});}catch(error){order=await recordCustomPayPalFailure(context.env,order.orderId,error);paymentWarning=error.message||'PayPal checkout could not be prepared.';}}
  return jsonResponse({ok:true,approval:customApprovalView(order),paymentWarning});}catch(error){return jsonResponse({ok:false,message:error.message||'Could not update custom order.'},error.status||500);}}
